// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

extension API.Objects {
  /// Autogenerated return type of CreateUser.
  static let CreateUserPayload = ApolloAPI.Object(
    typename: "CreateUserPayload",
    implementedInterfaces: []
  )
}