// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

extension API.Objects {
  /// Autogenerated return type of DeleteUser.
  static let DeleteUserPayload = ApolloAPI.Object(
    typename: "DeleteUserPayload",
    implementedInterfaces: []
  )
}