// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

extension API.Objects {
  /// Autogenerated return type of LoginUser.
  static let LoginUserPayload = ApolloAPI.Object(
    typename: "LoginUserPayload",
    implementedInterfaces: []
  )
}