// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

extension API.Objects {
  /// Autogenerated return type of LogoutUser.
  static let LogoutUserPayload = ApolloAPI.Object(
    typename: "LogoutUserPayload",
    implementedInterfaces: []
  )
}