// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

extension API.Objects {
  /// Autogenerated return type of UploadFile.
  static let UploadFilePayload = ApolloAPI.Object(
    typename: "UploadFilePayload",
    implementedInterfaces: []
  )
}